import profile from "../../public/images/advisers/Avatar.png";
const authorities = [
  {
    department: "Computer Science",
    headOfProgram: {
      name: "Dr. Olanloye",
      office: "Room 101",
      phone: "+2348038196016",
      image: profile,
      department: "Computer Science",
    },
    levelAdviser: [
      {
        name: "Mr. Erinfolami",
        office: "Room 101",
        phone: "+2349063630668",
        image: profile,
        department: "Computer Science",
        level: "100 level",
      },
      {
        name: "Mr. Adeniyi",
        office: "Room 101",
        phone: "+2348064056436",
        department: "Computer Science",
        image: profile,
        level: "200 level",
      },
      {
        name: "Mr. Adeyemo",
        office: "Room 101",
        phone: "+2348054774068",
        image: profile,
        department: "Computer Science",
        level: "300 level",
      },
      {
        name: "Dr. Ozichi",
        office: "Room 101",
        phone: "+2348037799290",
        image: profile,
        department: "Computer Science",
        level: "400 level",
      },
    ],
  },
  {
    department: "Cyber Security",
    headOfProgram: {
      name: "Dr. Popoola",
      office: "Room 101",
      image: profile,
      phone: "+234 xxxxxxxxxx",
      department: "Cyber Security",
    },
    levelAdviser: [
      {
        name: "Ms. Oluwadamilare",
        office: "Room 101",
        image: profile,
        phone: "+2348105644352",
        department: "Cyber Security",
        level: "100 level",
      },
      {
        name: "Mr. Falana",
        office: "Room 101",
        phone: "+2347030506455",
        image: profile,
        department: "Cyber Security",
        level: "200 level",
      },
      {
        name: "--",
        office: "--",
        phone: "--",
        image: profile,
        department: "Cyber Security",
        level: "300 level",
      },
      {
        name: "Mr. Erinfolami",
        office: "Room 101",
        phone: "+2349063630668",
        department: "Cyber Security",
        image: profile,
        level: "400 level",
      },
    ],
  },
  {
    department: "Information Technology",
    headOfProgram: {
      name: "Dr. G O Atanda",
      office: "Room 101",
      phone: "+234 xxxxxxxxxx",
      image: profile,
      department: "Information Technology",
    },
    levelAdviser: [
      {
        name: "Ms. Oluwadamilare",
        office: "Room 101",
        phone: "+2348105644352",
        department: "Information Technology",
        image: profile,
        level: "100 level",
      },
      {
        name: "Mr. Falana",
        office: "Room 101",
        phone: "+2347030506455",
        department: "Information Technology",
        level: "200 level",
        image: profile,
      },
      {
        name: "Mr. Falana",
        office: "Room 101",
        phone: "+2347030506455",
        department: "Information Technology",
        image: profile,
        level: "300 level",
      },
      {
        name: "Mr. Erinfolami",
        office: "Room 101",
        phone: "+2349063630668",
        department: "Information Technology",
        image: profile,
        level: "400 level",
      },
    ],
  },
  {
    department: "Software Engineering",
    headOfProgram: {
      name: "Dr. Umezurike",
      office: "Room 101",
      phone: "+2348033320364",
      image: profile,
      department: "Software Engineering",
    },
    levelAdviser: [
      {
        name: "Ms. Oluwadamilare",
        office: "Room 101",
        phone: "+2348105644352",
        image: profile,
        department: "Software Engineering",
        level: "100 level",
      },
      {
        name: "Mr. Oyebade",
        office: "Room 101",
        phone: "+2347033303729",
        image: profile,
        department: "Software Engineering",
        level: "200 level",
      },
      {
        name: "Mr. Oyebade",
        office: "Room 101",
        phone: "+2347033303729",
        image: profile,
        department: "Software Engineering",
        level: "300 level",
      },
      {
        name: "Dr. Ozichi",
        office: "Room 101",
        phone: "+234807799290",
        image: profile,
        department: "Software Engineering",
        level: "400 level",
      },
    ],
  },
];
export default authorities;
