import profile from "../../public/images/advisers/Avatar.png";
const authorities = [
  {
    department: "Computer Science",
    headOfProgram: {
      name: "Dr Olanloye",
      office: "Room 101",
      phone: "+2348038196016",
      image: profile,
      department: "Computer Science",
    },
    levelAdviser: [
      {
        name: "Mr. Erinfolami",
        office: "Room 101",
        phone: "+239063630668",
        image: profile,
        department: "Computer Science",
        level: "100 level",
      },
      {
        name: "Mr. Adeniyi",
        office: "Room 101",
        phone: "+2348064056436",
        department: "Computer Science",
        image: profile,
        level: "200 level",
      },
      {
        name: "Mr. Adeyemo",
        office: "Room 101",
        phone: "+2348054774068",
        image: profile,
        department: "Computer Science",
        level: "300 level",
      },
      {
        name: "Dr. Justice",
        office: "Room 101",
        phone: "+2348037799290",
        image: profile,
        department: "Computer Science",
        level: "400 level",
      },
    ],
  },
  {
    department: "Cyber Security",
    headOfProgram: {
      name: "Dr Olanloye",
      office: "Room 101",
      image: profile,
      phone: "+234 xxxxxxxxxx",
      department: "Computer Science",
    },
    levelAdviser: [
      {
        name: "Mrs Oluwadamilare",
        office: "Room 101",
        image: profile,
        phone: "+234xxxxxxxxxx",
        department: "Computer Science",
        level: "400 level",
      },
      {
        name: "Mrs Oluwadamilare",
        office: "Room 101",
        phone: "+234xxxxxxxxxx",
        image: profile,
        department: "Computer Science",
        level: "400 level",
      },
      {
        name: "Mrs Oluwadamilare",
        office: "Room 101",
        phone: "+234xxxxxxxxxx",
        department: "Computer Science",
        level: "400 level",
        image: profile,
      },
      {
        name: "Mrs Oluwadamilare",
        office: "Room 101",
        phone: "+234xxxxxxxxxx",
        department: "Computer Science",
        image: profile,
        level: "400 level",
      },
    ],
  },
  {
    department: "Information Technology",
    headOfProgram: {
      name: "Dr G O Atanda",
      office: "Room 101",
      phone: "+234 xxxxxxxxxx",
      image: profile,
      department: "Information Technology",
    },
    levelAdviser: [
      {
        name: "Mrs Oluwadamilare",
        office: "Room 101",
        phone: "+234xxxxxxxxxx",
        department: "Computer Science",
        image: profile,
        level: "400 level",
      },
      {
        name: "Mrs Oluwadamilare",
        office: "Room 101",
        phone: "+234xxxxxxxxxx",
        department: "Computer Science",
        level: "400 level",
        image: profile,
      },
      {
        name: "Mrs Oluwadamilare",
        office: "Room 101",
        phone: "+234xxxxxxxxxx",
        department: "Computer Science",
        image: profile,
        level: "400 level",
      },
      {
        name: "Mrs Oluwadamilare",
        office: "Room 101",
        phone: "+234xxxxxxxxxx",
        department: "Computer Science",
        image: profile,
        level: "400 level",
      },
    ],
  },
  {
    department: "Software Engineering",
    headOfProgram: {
      name: "Dr Olanloye",
      office: "Room 101",
      phone: "+234 xxxxxxxxxx",
      image: profile,
      department: "Computer Science",
    },
    levelAdviser: [
      {
        name: "Mrs Oluwadamilare",
        office: "Room 101",
        phone: "+234xxxxxxxxxx",
        image: profile,
        department: "Computer Science",
        level: "400 level",
      },
      {
        name: "Mrs Oluwadamilare",
        office: "Room 101",
        phone: "+234xxxxxxxxxx",
        image: profile,
        department: "Computer Science",
        level: "400 level",
      },
      {
        name: "Mrs Oluwadamilare",
        office: "Room 101",
        phone: "+234xxxxxxxxxx",
        image: profile,
        department: "Computer Science",
        level: "400 level",
      },
      {
        name: "Mrs Oluwadamilare",
        office: "Room 101",
        phone: "+234xxxxxxxxxx",
        image: profile,
        department: "Computer Science",
        level: "400 level",
      },
    ],
  },
];
export default authorities;
